spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/MilindMP/E-Commerse-ShopSphere.git
          search-paths:
            - cart-service/src/main/resources
            - user-service/src/main/resources
          clone-on-start: true

server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/